### PR TITLE
Add Elixir solution for problem 1

### PR DESCRIPTION
**Pull request by gentilfp**
Probably not the best solution, still learning here :smile: 
### Elixir

``` elixir
$ elixir solutions/problem_1/solution.ex
=> Result: 233168
=> Time: 0.000045
```

### CODE REVIEW

**Comment by mdsrosa** [comment]
That's awesome! Thanks! 
But please, don't be like @duduribeiro (start studying a language, solves one problem and then disappears hahaha) and keep solving the other problems with Elixir as well. That would be great. :smile: :sunglasses:

**Comment by duduribeiro** [comment]
:fu:

**Comment by duduribeiro** [comment]
kkkkkkkkkkk.. I have other things to do :P

Trying to find time to help this :(

**Comment by gentilfp** [comment]
AEHUHEAUHAEUHAE already working on the problem 2

**Comment by mdsrosa** [comment]
@duduribeiro Yeah. Sure. Hahaha :-)
@fpgentil Nice! Good for you!

**Pull request merged**
